sudo: required
dist: trusty

services:
  - docker

language: node_js
  - "7.10"

notifications:
  email: false

before_script:
  - sudo service postgresql stop || true
  - docker-compose up -d
  - sleep 10
  - docker exec postgres /bin/bash -c "psql -U postgres -c 'CREATE DATABASE development'"

script:
  - docker exec pa.to /bin/sh -c "npm install && ./node_modules/.bin/sequelize db:migrate && npm test"

after_script:
  - docker-compose down
