app:
  build: .
  container_name: pa.to
  dockerfile: Dockerfile
  command: bash -c 'while [ true ]; do sleep 10; done'
  environment:
    - NODE_ENV=development
    - REDIS_MASTER_SERVICE_PORT=6379
    - REDIS_MASTER_SERVICE_HOST=redis_pato
  volumes:
    - '.:/app'
  ports:
    - 9003:9003
  expose:
    - 9003
  links:
    - db:db
    - cache:cache

db:
  image: postgres:9.5.4
  container_name: postgres
  ports:
    - 5432:5432
  expose:
    - 5432
  environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres

cache:
  image: redis:3.0.7
  container_name: redis_pato
  ports:
    - 6379:6379
  expose:
    - 6379