apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb
spec:
  ports:
  - port: 8080
    targetPort: admin
    name: admin
  - port: 28015
    targetPort: driver
    name: driver
  - port: 29015
    targetPort: cluster
    name: cluster
  selector:
    db: rethinkdb